	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x40010000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
	
Reset_Handler
	LDR R5,=SRC1
	LDR R6,=SRC2
	LDR R1,[R5]
	LDR R2,[R6]
	MOV R3,#0
UP
	SUB R1,R2
	ADD R3,#1
	CMP R2,R1
	BLS UP
	LDR R5,=QUOTIENT
	LDR R6,=REMAINDER
	STR R3,[R5]
	STR R1,[R6]
STOP 
	B STOP
SRC1 DCD 0xFFFFFFFF
SRC2 DCD 0x0000FFFF
	AREA DATASEG,DATA,READWRITE
QUOTIENT DCD 0
REMAINDER DCD 0