	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0X4000000
	DCD Reset_Handler
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0,=SRC
	LDR R1,=DST
	LDR R3,[R0]
	STR R3,[R1]
STOP 
	B STOP
SRC DCB 8,0X12
	AREA DATASEG,DATA,READWRITE
DST DCD 0X12345678
	END