	AREA RESET,DATA,READONLY
	EXPORT __Vectors

__Vectors
	DCD 0X40001000
	DCD Reset_Handler
	
	ALIGN

	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
	
Reset_Handler
	LDR R0,=SRC1 + 12
	LDR R1,=SRC2 + 12
	LDR R5,=DST + 12
	MOV R8,#4
UP
	LDR R3,[R0]
	LDR R4,[R2]
	ADDS R6,R5,R4
	STR R6,[R5]
	SUB R0,#4
	SUB R1,#4
	SUB R5,#4
	SUB R8,#1
	CMP R8,#0
	BNE UP
STOP
	B STOP
	
SRC1 DCD 0xAAAAAAAA,0xBBBBBBBB,0xCCCCCCCC,0xDDDDDDDD
SRC2 DCD 0xAAAAAAAA,0xBBBBBBBB,0xCCCCCCCC,0xDDDDDDDD

	AREA DATASEG,DATA,READWRITE
DST DCD 0
	
	END