	AREA RESET,DATA,READONLY
	EXPORT __Vectors

__Vectors
	DCD 0X40001000
	DCD Reset_Handler
	
	ALIGN

	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
	
Reset_Handler
	LDR R0,=SRC1
    LDR R1,=SRC2
    LDR R2,=DST
    MOV R5,#0
    MOV R7,#4
    MRS R6,PSR
    ORR R6,#0X20000000
    MSR PSR,R6
UP
    LDR R3,[R0],#4
    LDR R4,[R1],#4
    SBCS R5,R3,R4
    STR R5,[R2],#4
    SUBS R7,#1
    BNE UP
STOP
	B STOP
	
SRC1 DCD 0xAAAAAAAA,0xBBBBBBBB,0xCCCCCCCC,0xDDDDDDDD
SRC2 DCD 0xAAAAAAAA,0xBBBBBBBB,0xCCCCCCCC,0xDDDDDDDD

	AREA DATASEG,DATA,READWRITE
DST DCD 0
	
	END